export interface CensoPacienteI {
  HPNESTANC: number;
  ADNINGRESO: number;
  ADNCENATE: number;
  DIACODIGO: string; //
  DIANOMBRE: string; //
  GCMHOSCAN: number; //
  GCMUCICAN: number; //
  GCMUNCUIN: number; //
  GENARESER: number; //
  GENDETCON: number; //
  GENDIAGNO: number; //
  GENPACIEN: number; //
  GENPRESAL: number; //
  HESFECSAL: Date; //
  HGRCODIGO: string; //
  HGRNOMBRE: string; //
  HPNDEFCAM: number; //
  HCACODIGO: string; //CAMA
  GPADOCPAC: string; //DOCUMENTO PACIENTE
  GPANOMPAC: string; //NOMBRE PACIENTE
  GPAEDAPAC: number; //EDAD PACIENTE
  AINDIAEST: number; //DIAS ESTANCIA
  GDENOMBRE: string; //CONTRATO
  GASNOMBRE: string; //AREA DE SERVICIO
  ACACODIGO: string; //CODIGO CENTRO DE ATENCION
  ACANOMBRE: string; //NOMBRE DE CENTRO DE ATENCION
  GPADIRECC: string; //DIRECCION DE PACIENTE
  GPATELEFO: string; //TELEFONO PACIENTE
  GPAMUNPAC: string; //MUNICIPIO PACIENTE
  AINACONOM: string; //FAMILIAR
  AINACOTEL: string; //FAMILIAR TELEFONO
  AINACUNOM: string; //ACUDIENTE
  AINACUTEL: string; //TELEFONO ACUDIENTE
  AINACUPAR: string; //PARENTEZCO ACUDIENTE
  AINCAUING: string; //CAUSA DE INGRESO
  AINURGCON: string; //FORMA DE INGRESO
  PRECODIGO: string; //ENTIDAD REMISION
  PRENOMBRE: string; //ENTIDAD REMISION
  GASCODIGO: string; //CODIGO DE AREA DE SERVICIO
  HCANOMBRE: string; //UBICACION CAMA
  HSUCODIGO: string; //CODIGO SUBGRUPO
  HSUNOMBRE: string; //NOMBRE SUBGRUPO
  GDECODIGO: string; //CODIGO EPS
  AINCONSEC: number; //INGRESO
  AINFECING: Date; //FECHA
  GPASEXPAC: string; //SEXO 1 HOMBRE, 2 MUJER
  GPAESTPAC: string; //ESTRATO
  GPATIPAFI: string; //AFILIACION
}
